services:
  backend:
    build: ./Backend
    ports:
      - 8080:8080
    networks:
      - project 
    
  frontend:
    build: ./Frontend
    ports: 
      - 8081:80
    depends_on:
      - backend
    
networks:
  project:
    external: true